image: node:20

stages:
  - test
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install-and-test:
  stage: test
  script:
    - npm ci
    - npm test -- --watchAll=false

production-build:
  stage: build
  script:
    - npm ci
    - npm run build